---
- name: env var
  hosts: all
  become: true
  environment:
    wish: "hi.txt"
  tasks:
    - name: use env var
      file:
        path: /opt/$wish
        state: touch

    - name: task level env var
      environment:
        wish: "welcome.txt"
      file:
        path: /opt/$wish
        state: touch
