---
- name: vars example
  hosts: all
  become: true
  vars:
    name: "pavan"
    age: "20"
    code: "009"
  tasks:
    - name: testings name var
      debug:
        var: name
    - name: testing age var
      debug:
        var: age
    - name: testing code var
      debug:
        var: code
